### PR TITLE
Feature/vehiclelist

### PR DESCRIPTION
**Pull request by rmuehler**
We added routing and displaying of Vehicle components, just waiting on the service #14 so we can inject that.

### CODE REVIEW

**Review by GannonDeWalt — APPROVED** [review]
Lookds good!

**Review by raaedk — COMMENTED** [review]
looks good

**Review by raaedk — APPROVED** [review]
looks good

**Review by GannonDeWalt — APPROVED** [review]
Looks good!

**Review by raaedk — APPROVED** [review]

**Pull request merged**
