### PR TITLE
Feature/submission component

### PR DESCRIPTION
**Pull request by rmuehler**
Submission component:

- Gets form data and adds to a vehicle
- Converts uploaded images to base64 for storing in database
- Sends sends a POST request to API on submit

Does not yet

- Validate input locally, besides checking that every field is filled out

### CODE REVIEW

**Review by wangscs — APPROVED** [review]
Nice!

**Review by raaedk — APPROVED** [review]
cool

**Review by GannonDeWalt — APPROVED** [review]
Looks good

**Review by ammitchky — APPROVED** [review]
looks good

**Pull request merged**
